# Generated by Django 3.1.7 on 2021-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotSelect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='slotid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
