image: python:3.8

cache:
  key: ${CI_COMMIT_REF_SLUG} 
  paths:
    - venv

stages:
  - build

django check:
  stage: build
  script:
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - pip3 install pylint pylint-gitlab pylint-exit pylint-django
    - python3 manage.py check
    - pylint --load-plugins pylint_django --disable=C0114,C0115,C0116 --output-format=pylint_gitlab.GitlabCodeClimateReporter ORS calendarManager config dashboard login meeting message slotSelect > code-quality.json || pylint-exit $?
  artifacts:
    reports:
      codequality: code-quality.json
