version: "3.8"
services:
  ors:
    build: .
    ports: 
      - "8000:80"
    # env_file:
    #  - {envfile location}
    volumes:
      - .:/opt/ors
    depends_on:
      - mysql
    command: ["python3 manage.py runserver"]
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    # env_file:
    #  - {envfile location}
    volumes:
      - "ors-data:/var/lib/mysql"
volumes:
  ors-data:
    driver: local