# Generated by Django 3.1.7 on 2021-03-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetingid', models.AutoField(db_column='meetingID', primary_key=True, serialize=False)),
                ('hostid', models.IntegerField(db_column='hostID')),
                ('participantid', models.IntegerField(db_column='participantID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('statusid', models.IntegerField(blank=True, db_column='statusID', null=True)),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('typeid', models.CharField(blank=True, db_column='typeID', max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('hashpw', models.CharField(blank=True, db_column='hashPW', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
