# Generated by Django 3.1.7 on 2021-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gp',
            fields=[
                ('groupid', models.AutoField(db_column='groupID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(blank=True, db_column='groupName', max_length=255, null=True)),
                ('groupownerid', models.IntegerField(db_column='groupOwnerID')),
            ],
            options={
                'db_table': 'gp',
            },
        ),
        migrations.CreateModel(
            name='Groupmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField(db_column='groupID')),
                ('memberid', models.IntegerField(db_column='memberID')),
                ('joindate', models.DateTimeField(blank=True, db_column='joinDate', null=True)),
            ],
            options={
                'db_table': 'groupmember',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetingid', models.AutoField(db_column='meetingID', primary_key=True, serialize=False)),
                ('hostid', models.IntegerField(db_column='hostID')),
                ('participantid', models.IntegerField(db_column='participantID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('statusid', models.IntegerField(blank=True, db_column='statusID', null=True)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='messageID', primary_key=True, serialize=False)),
                ('senderid', models.IntegerField(db_column='senderID')),
                ('receiverid', models.IntegerField(db_column='receiverID')),
                ('referenceid', models.IntegerField(blank=True, db_column='referenceID', null=True)),
                ('sendtime', models.DateTimeField(blank=True, db_column='sendTime', null=True)),
                ('viewed', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slotid', models.AutoField(db_column='slotID', primary_key=True, serialize=False)),
                ('ownerid', models.IntegerField(db_column='ownerID')),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(db_column='endTime')),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.CreateModel(
            name='Slotsopento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotsid', models.IntegerField(db_column='slotsID')),
                ('isgroup', models.IntegerField(blank=True, db_column='isGroup', null=True)),
                ('opentoid', models.IntegerField(db_column='OpenToID')),
            ],
            options={
                'db_table': 'slotsopento',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('typeid', models.CharField(blank=True, db_column='typeID', max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('hashpw', models.CharField(blank=True, db_column='hashPW', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Useravailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userID')),
                ('date', models.DateField()),
                ('slotid', models.IntegerField(db_column='slotID')),
            ],
            options={
                'db_table': 'useravailability',
            },
        ),
    ]
