# Generated by Django 3.1.7 on 2021-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210324_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='group',
            field=models.IntegerField(db_column='groupID', default=-1),
            preserve_default=False,
        ),
    ]
