# Generated by Django 3.1.7 on 2021-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_slot_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='group',
            new_name='groupid',
        ),
    ]
