# Generated by Django 3.1.7 on 2021-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210325_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupdetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField()),
            ],
        ),
    ]
