# Generated by Django 3.1.7 on 2021-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_groupdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetail',
            name='min_required_slot',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
