# Generated by Django 3.1.7 on 2021-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_groupdetail_min_required_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
