# Generated by Django 3.1.7 on 2021-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_message_meetingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
