# Generated by Django 3.1.7 on 2021-04-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210407_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='Gp',
        ),
        migrations.DeleteModel(
            name='Groupmember',
        ),
        migrations.DeleteModel(
            name='Slotsopento',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Useravailability',
        ),
    ]
