# Generated by Django 3.1.7 on 2021-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currentphase',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('phase1_start', models.DateTimeField()),
                ('phase1_end', models.DateTimeField()),
                ('phase1_group_name', models.CharField(max_length=150)),
                ('phase2_start', models.DateTimeField()),
                ('phase2_end', models.DateTimeField()),
                ('phase2_group_name', models.CharField(max_length=150)),
                ('phase3_start', models.DateTimeField()),
            ],
        ),
    ]
